[package]
name = "automergeable-traits"
version = "0.1.0"
authors = ["Andrew Jeffery <dev@jeffas.io>"]
edition = "2018"
license = "MIT"

[dependencies]
automerge = { git = "https://github.com/jeffa5/automerge-rs", branch = "fix-panic-in-change" }
automerge-protocol = { git = "https://github.com/jeffa5/automerge-rs", branch = "fix-panic-in-change" }
thiserror = "1.0.24"
serde_json = "1.0.62"
